### ISSUE TITLE
Implement connectors status sub-command

### ISSUE THREAD

**Issue by richardcase** [90poe/connectctl#6] opened 2019-08-19 15:20 UTC
Implement `connectctl connectors status` that given a list of connector names it will return the status of those connectors. It should allow outputing the results to JSON and table.

This relates to the following API call: https://docs.confluent.io/current/connect/references/restapi.html#get--connectors-(string-name)-status

**Comment by mdevilliers** [comment] 2020-04-17 10:27
Closing as duplicate of #12

**Closed by mdevilliers** 2020-04-17 10:27 UTC
Labels: enhancement, good first issue, help wanted
